// src/main/webapp/app/entities/asset/update/asset-update.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
import { ActivatedRoute } from '@angular/router';
import { Observable } from 'rxjs';
import { finalize, map } from 'rxjs/operators';

import SharedModule from 'app/shared/shared.module';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';

import { IOrganisation } from 'app/entities/organisation/organisation.model';
import { OrganisationService } from 'app/entities/organisation/service/organisation.service';
import { AssetType } from 'app/entities/enumerations/asset-type.model';
import { AssetService } from '../service/asset.service';
import { IAsset } from '../asset.model';
import { AssetFormService, AssetFormGroup } from './asset-form.service';

@Component({
  standalone: true,
  selector: 'jhi-asset-update',
  templateUrl: './asset-update.component.html',
  imports: [SharedModule, FormsModule, ReactiveFormsModule],
})
export class AssetUpdateComponent implements OnInit {
  isSaving = false;
  asset: IAsset | null = null;
  assetTypeValues = Object.keys(AssetType);

  organisationsSharedCollection: IOrganisation[] = [];
  assetsSharedCollection: IAsset[] = [];

  editForm: AssetFormGroup = this.assetFormService.createAssetFormGroup();

  constructor(
    protected assetService: AssetService,
    protected assetFormService: AssetFormService,
    protected organisationService: OrganisationService,
    protected activatedRoute: ActivatedRoute,
  ) {}

  compareOrganisation = (o1: IOrganisation | null, o2: IOrganisation | null): boolean =>
    this.organisationService.compareOrganisation(o1, o2);

  compareAsset = (o1: IAsset | null, o2: IAsset | null): boolean => this.assetService.compareAsset(o1, o2);

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ asset }) => {
      this.asset = asset;
      if (asset) {
        this.updateForm(asset);
      }

      this.loadRelationshipsOptions();
    });
  }

  previousState(): void {
    window.history.back();
  }

  save(): void {
    this.isSaving = true;
    const asset = this.assetFormService.getAsset(this.editForm);
    if (asset.id !== null) {
      this.subscribeToSaveResponse(this.assetService.update(asset));
    } else {
      this.subscribeToSaveResponse(this.assetService.create(asset));
    }
  }

  protected subscribeToSaveResponse(result: Observable<HttpResponse<IAsset>>): void {
    result.pipe(finalize(() => this.onSaveFinalize())).subscribe({
      next: () => this.onSaveSuccess(),
      error: () => this.onSaveError(),
    });
  }

  protected onSaveSuccess(): void {
    this.previousState();
  }

  protected onSaveError(): void {
    // Api for inheritance.
  }

  protected onSaveFinalize(): void {
    this.isSaving = false;
  }

  protected updateForm(asset: IAsset): void {
    this.asset = asset;
    this.assetFormService.resetForm(this.editForm, asset);

    this.organisationsSharedCollection = this.organisationService.addOrganisationToCollectionIfMissing<IOrganisation>(
      this.organisationsSharedCollection,
      asset.orga,
    );
    this.assetsSharedCollection = this.assetService.addAssetToCollectionIfMissing<IAsset>(
      this.assetsSharedCollection,
      asset.parent,
      ...(asset.childrens ?? []),
    );
  }

  protected loadRelationshipsOptions(): void {
    this.organisationService
      .query()
      .pipe(map((res: HttpResponse<IOrganisation[]>) => res.body ?? []))
      .pipe(
        map((organisations: IOrganisation[]) =>
          this.organisationService.addOrganisationToCollectionIfMissing<IOrganisation>(organisations, this.asset?.orga),
        ),
      )
      .subscribe((organisations: IOrganisation[]) => (this.organisationsSharedCollection = organisations));

    this.assetService
      .query()
      .pipe(map((res: HttpResponse<IAsset[]>) => res.body ?? []))
      .pipe(
        map((assets: IAsset[]) =>
          this.assetService.addAssetToCollectionIfMissing<IAsset>(assets, this.asset?.parent, ...(this.asset?.childrens ?? [])),
        ),
      )
      .subscribe((assets: IAsset[]) => (this.assetsSharedCollection = assets));
  }
}

<div class="d-flex justify-content-center">
  <div class="col-8">
    <form name="editForm" role="form" novalidate (ngSubmit)="save()" [formGroup]="editForm">
      <h2 id="jhi-asset-heading" data-cy="AssetCreateUpdateHeading" jhiTranslate="treeportApp.asset.home.createOrEditLabel">
        Create or edit a Asset
      </h2>

      <div>
        <jhi-alert-error></jhi-alert-error>

        <div class="mb-3" *ngIf="editForm.controls.id.value !== null">
          <label class="form-label" jhiTranslate="global.field.id" for="field_id">ID</label>
          <input type="text" class="form-control" name="id" id="field_id" data-cy="id" formControlName="id" [readonly]="true" />
        </div>

        <div class="mb-3">
          <label class="form-label" jhiTranslate="treeportApp.asset.name" for="field_name">Name</label>
          <input type="text" class="form-control" name="name" id="field_name" data-cy="name" formControlName="name" />
        </div>

        <div class="mb-3">
          <label class="form-label" jhiTranslate="treeportApp.asset.type" for="field_type">Type</label>
          <select class="form-control" name="type" formControlName="type" id="field_type" data-cy="type">
            <option [ngValue]="null">{{ 'treeportApp.AssetType.null' | translate }}</option>
            <option *ngFor="let assetType of assetTypeValues" [value]="assetType">
              {{ 'treeportApp.AssetType.' + assetType | translate }}
            </option>
          </select>
        </div>

        <div class="mb-3">
          <label class="form-label" jhiTranslate="treeportApp.asset.orga" for="field_orga">Orga</label>
          <select
            class="form-control"
            id="field_orga"
            data-cy="orga"
            name="orga"
            formControlName="orga"
            [compareWith]="compareOrganisation"
          >
            <option [ngValue]="null"></option>
            <option [ngValue]="organisationOption" *ngFor="let organisationOption of organisationsSharedCollection">
              {{ organisationOption.id }}
            </option>
          </select>
        </div>

        <div class="mb-3">
          <label class="form-label" jhiTranslate="treeportApp.asset.parent" for="field_parent">Parent</label>
          <select
            class="form-control"
            id="field_parent"
            data-cy="parent"
            name="parent"
            formControlName="parent"
            [compareWith]="compareAsset"
          >
            <option [ngValue]="null"></option>
            <option [ngValue]="assetOption" *ngFor="let assetOption of assetsSharedCollection">{{ assetOption.id }}</option>
          </select>
        </div>

        <div class="mb-3">
          <label jhiTranslate="treeportApp.asset.childrens" for="field_childrens">Childrens</label>
          <select
            class="form-control"
            id="field_childrens"
            data-cy="childrens"
            multiple
            name="childrens"
            formControlName="childrens"
            [compareWith]="compareAsset"
          >
            <option [ngValue]="assetOption" *ngFor="let assetOption of assetsSharedCollection">{{ assetOption.id }}</option>
          </select>
        </div>
      </div>

      <div>
        <button type="button" id="cancel-save" data-cy="entityCreateCancelButton" class="btn btn-secondary" (click)="previousState()">
          <fa-icon icon="ban"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
        </button>

        <button
          type="submit"
          id="save-entity"
          data-cy="entityCreateSaveButton"
          [disabled]="editForm.invalid || isSaving"
          class="btn btn-primary"
        >
          <fa-icon icon="save"></fa-icon>&nbsp;<span jhiTranslate="entity.action.save">Save</span>
        </button>
      </div>
    </form>
  </div>
</div>

// src/main/webapp/app/entities/asset/asset-update.tsx
import React, { useState, useEffect } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { Button, Row, Col, FormText } from 'reactstrap';
import { isNumber, Translate, translate, ValidatedField, ValidatedForm } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { convertDateTimeFromServer, convertDateTimeToServer, displayDefaultDateTime } from 'app/shared/util/date-utils';
import { mapIdList } from 'app/shared/util/entity-utils';
import { useAppDispatch, useAppSelector } from 'app/config/store';

import { IOrganisation } from 'app/shared/model/organisation.model';
import { getEntities as getOrganisations } from 'app/entities/organisation/organisation.reducer';
import { getEntities as getAssets } from 'app/entities/asset/asset.reducer';
import { IAsset } from 'app/shared/model/asset.model';
import { AssetType } from 'app/shared/model/enumerations/asset-type.model';
import { getEntity, updateEntity, createEntity, reset } from './asset.reducer';

export const AssetUpdate = () => {
  const dispatch = useAppDispatch();

  const navigate = useNavigate();

  const { id } = useParams<'id'>();
  const isNew = id === undefined;

  const organisations = useAppSelector(state => state.organisation.entities);
  const assets = useAppSelector(state => state.asset.entities);
  const assetEntity = useAppSelector(state => state.asset.entity);
  const loading = useAppSelector(state => state.asset.loading);
  const updating = useAppSelector(state => state.asset.updating);
  const updateSuccess = useAppSelector(state => state.asset.updateSuccess);
  const assetTypeValues = Object.keys(AssetType);

  const handleClose = () => {
    navigate('/asset' + location.search);
  };

  useEffect(() => {
    if (isNew) {
      dispatch(reset());
    } else {
      dispatch(getEntity(id));
    }

    dispatch(getOrganisations({}));
    dispatch(getAssets({}));
  }, []);

  useEffect(() => {
    if (updateSuccess) {
      handleClose();
    }
  }, [updateSuccess]);

  // eslint-disable-next-line complexity
  const saveEntity = values => {
    const entity = {
      ...assetEntity,
      ...values,
      childrens: mapIdList(values.childrens),
      orga: organisations.find(it => it.id.toString() === values.orga.toString()),
      parent: assets.find(it => it.id.toString() === values.parent.toString()),
    };

    if (isNew) {
      dispatch(createEntity(entity));
    } else {
      dispatch(updateEntity(entity));
    }
  };

  const defaultValues = () =>
    isNew
      ? {}
      : {
          type: 'SITE',
          ...assetEntity,
          orga: assetEntity?.orga?.id,
          parent: assetEntity?.parent?.id,
          childrens: assetEntity?.childrens?.map(e => e.id.toString()),
        };

  return (
    <div>
      <Row className="justify-content-center">
        <Col md="8">
          <h2 id="treeportApp.asset.home.createOrEditLabel" data-cy="AssetCreateUpdateHeading">
            <Translate contentKey="treeportApp.asset.home.createOrEditLabel">Create or edit a Asset</Translate>
          </h2>
        </Col>
      </Row>
      <Row className="justify-content-center">
        <Col md="8">
          {loading ? (
            <p>Loading...</p>
          ) : (
            <ValidatedForm defaultValues={defaultValues()} onSubmit={saveEntity}>
              {!isNew ? (
                <ValidatedField
                  name="id"
                  required
                  readOnly
                  id="asset-id"
                  label={translate('global.field.id')}
                  validate={{ required: true }}
                />
              ) : null}
              <ValidatedField label={translate('treeportApp.asset.name')} id="asset-name" name="name" data-cy="name" type="text" />
              <ValidatedField label={translate('treeportApp.asset.type')} id="asset-type" name="type" data-cy="type" type="select">
                {assetTypeValues.map(assetType => (
                  <option value={assetType} key={assetType}>
                    {translate('treeportApp.AssetType.' + assetType)}
                  </option>
                ))}
              </ValidatedField>
              <ValidatedField id="asset-orga" name="orga" data-cy="orga" label={translate('treeportApp.asset.orga')} type="select">
                <option value="" key="0" />
                {organisations
                  ? organisations.map(otherEntity => (
                      <option value={otherEntity.id} key={otherEntity.id}>
                        {otherEntity.id}
                      </option>
                    ))
                  : null}
              </ValidatedField>
              <ValidatedField id="asset-parent" name="parent" data-cy="parent" label={translate('treeportApp.asset.parent')} type="select">
                <option value="" key="0" />
                {assets
                  ? assets.map(otherEntity => (
                      <option value={otherEntity.id} key={otherEntity.id}>
                        {otherEntity.id}
                      </option>
                    ))
                  : null}
              </ValidatedField>
              <ValidatedField
                label={translate('treeportApp.asset.childrens')}
                id="asset-childrens"
                data-cy="childrens"
                type="select"
                multiple
                name="childrens"
              >
                <option value="" key="0" />
                {assets
                  ? assets.map(otherEntity => (
                      <option value={otherEntity.id} key={otherEntity.id}>
                        {otherEntity.id}
                      </option>
                    ))
                  : null}
              </ValidatedField>
              <Button tag={Link} id="cancel-save" data-cy="entityCreateCancelButton" to="/asset" replace color="info">
                <FontAwesomeIcon icon="arrow-left" />
                &nbsp;
                <span className="d-none d-md-inline">
                  <Translate contentKey="entity.action.back">Back</Translate>
                </span>
              </Button>
              &nbsp;
              <Button color="primary" id="save-entity" data-cy="entityCreateSaveButton" type="submit" disabled={updating}>
                <FontAwesomeIcon icon="save" />
                &nbsp;
                <Translate contentKey="entity.action.save">Save</Translate>
              </Button>
            </ValidatedForm>
          )}
        </Col>
      </Row>
    </div>
  );
};

export default AssetUpdate;
