// src/main/webapp/app/entities/asset/detail/asset-detail.component.ts
import { Component, Input } from '@angular/core';
import { ActivatedRoute, RouterModule } from '@angular/router';

import SharedModule from 'app/shared/shared.module';
import { DurationPipe, FormatMediumDatetimePipe, FormatMediumDatePipe } from 'app/shared/date';
import { IAsset } from '../asset.model';

@Component({
  standalone: true,
  selector: 'jhi-asset-detail',
  templateUrl: './asset-detail.component.html',
  imports: [SharedModule, RouterModule, DurationPipe, FormatMediumDatetimePipe, FormatMediumDatePipe],
})
export class AssetDetailComponent {
  @Input() asset: IAsset | null = null;

  constructor(protected activatedRoute: ActivatedRoute) {}

  previousState(): void {
    window.history.back();
  }
}

<div class="d-flex justify-content-center">
  <div class="col-8">
    <div *ngIf="asset">
      <h2 data-cy="assetDetailsHeading"><span jhiTranslate="treeportApp.asset.detail.title">Asset</span></h2>

      <hr />

      <jhi-alert-error></jhi-alert-error>

      <jhi-alert></jhi-alert>

      <dl class="row-md jh-entity-details">
        <dt><span jhiTranslate="global.field.id">ID</span></dt>
        <dd>
          <span>{{ asset.id }}</span>
        </dd>
        <dt><span jhiTranslate="treeportApp.asset.name">Name</span></dt>
        <dd>
          <span>{{ asset.name }}</span>
        </dd>
        <dt><span jhiTranslate="treeportApp.asset.type">Type</span></dt>
        <dd>
          <span jhiTranslate="{{ 'treeportApp.AssetType.' + asset.type }}">{{ asset.type }}</span>
        </dd>
        <dt><span jhiTranslate="treeportApp.asset.orga">Orga</span></dt>
        <dd>
          <div *ngIf="asset.orga">
            <a [routerLink]="['/organisation', asset.orga.id, 'view']">{{ asset.orga.id }}</a>
          </div>
        </dd>
        <dt><span jhiTranslate="treeportApp.asset.parent">Parent</span></dt>
        <dd>
          <div *ngIf="asset.parent">
            <a [routerLink]="['/asset', asset.parent.id, 'view']">{{ asset.parent.id }}</a>
          </div>
        </dd>
        <dt><span jhiTranslate="treeportApp.asset.childrens">Childrens</span></dt>
        <dd>
          <span *ngFor="let childrens of asset.childrens; let last = last">
            <a [routerLink]="['/asset', childrens.id, 'view']">{{ childrens.id }}</a
            >{{ last ? '' : ', ' }}
          </span>
        </dd>
      </dl>

      <button type="submit" (click)="previousState()" class="btn btn-info" data-cy="entityDetailsBackButton">
        <fa-icon icon="arrow-left"></fa-icon>&nbsp;<span jhiTranslate="entity.action.back">Back</span>
      </button>

      <button type="button" [routerLink]="['/asset', asset.id, 'edit']" class="btn btn-primary">
        <fa-icon icon="pencil-alt"></fa-icon>&nbsp;<span jhiTranslate="entity.action.edit">Edit</span>
      </button>
    </div>
  </div>
</div>

// src/main/webapp/app/entities/asset/asset-detail.tsx
import React, { useEffect } from 'react';
import { Link, useParams } from 'react-router-dom';
import { Button, Row, Col } from 'reactstrap';
import { Translate } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { useAppDispatch, useAppSelector } from 'app/config/store';

import { getEntity } from './asset.reducer';

export const AssetDetail = () => {
  const dispatch = useAppDispatch();

  const { id } = useParams<'id'>();

  useEffect(() => {
    dispatch(getEntity(id));
  }, []);

  const assetEntity = useAppSelector(state => state.asset.entity);
  return (
    <Row>
      <Col md="8">
        <h2 data-cy="assetDetailsHeading">
          <Translate contentKey="treeportApp.asset.detail.title">Asset</Translate>
        </h2>
        <dl className="jh-entity-details">
          <dt>
            <span id="id">
              <Translate contentKey="global.field.id">ID</Translate>
            </span>
          </dt>
          <dd>{assetEntity.id}</dd>
          <dt>
            <span id="name">
              <Translate contentKey="treeportApp.asset.name">Name</Translate>
            </span>
          </dt>
          <dd>{assetEntity.name}</dd>
          <dt>
            <span id="content">
              <Translate contentKey="treeportApp.asset.content">Content</Translate>
            </span>
          </dt>
          <dd>{assetEntity.content}</dd>
          <dt>
            <span id="type">
              <Translate contentKey="treeportApp.asset.type">Type</Translate>
            </span>
          </dt>
          <dd>{assetEntity.type}</dd>
          <dt>
            <Translate contentKey="treeportApp.asset.orga">Orga</Translate>
          </dt>
          <dd>{assetEntity.orga ? assetEntity.orga.id : ''}</dd>
          <dt>
            <Translate contentKey="treeportApp.asset.parent">Parent</Translate>
          </dt>
          <dd>{assetEntity.parent ? assetEntity.parent.id : ''}</dd>
          <dt>
            <Translate contentKey="treeportApp.asset.childrens">Childrens</Translate>
          </dt>
          <dd>
            {assetEntity.childrens
              ? assetEntity.childrens.map((val, i) => (
                  <span key={val.id}>
                    <a>{val.id}</a>
                    {assetEntity.childrens && i === assetEntity.childrens.length - 1 ? '' : ', '}
                  </span>
                ))
              : null}
          </dd>
        </dl>
        <Button tag={Link} to="/asset" replace color="info" data-cy="entityDetailsBackButton">
          <FontAwesomeIcon icon="arrow-left" />{' '}
          <span className="d-none d-md-inline">
            <Translate contentKey="entity.action.back">Back</Translate>
          </span>
        </Button>
        &nbsp;
        <Button tag={Link} to={`/asset/${assetEntity.id}/edit`} replace color="primary">
          <FontAwesomeIcon icon="pencil-alt" />{' '}
          <span className="d-none d-md-inline">
            <Translate contentKey="entity.action.edit">Edit</Translate>
          </span>
        </Button>
      </Col>
    </Row>
  );
};

export default AssetDetail;
